import test from 'node:test';
import assert from 'node:assert/strict';
import * as core from '../src/core.js';
const t = () => ({format:'maker-template-1', id:'orbita', version:'1.0.0', name:'Órbita', description:'Una plantilla propia', layout:'classic', hero:'split', columns:4, sections:['hero','categories','catalog','features','faq'], materials:['flat','glass','metal']});

test('valid template is parsed and cloned', () => { const a=t(); assert.deepEqual(core.parseTemplate(a),a); assert.notEqual(core.parseTemplate(a),a); });
test('unknown keys, prototype keys, arbitrary html and new components are rejected', () => { for (const v of [{...t(),html:'<script>alert(1)</script>'},{...t(),columns:100},{...t(),layout:'javascript:alert(1)'},{...t(),sections:['hero','hero']},{...t(),sections:['unknown']},JSON.parse(JSON.stringify(t()).replace('"id":','"__proto__":{},"id":'))]) assert.throws(()=>core.parseTemplate(v)); });
test('future versions, invalid IDs and oversized text are rejected', () => { for(const v of [{...t(),format:'maker-template-2'},{...t(),id:'../evil'},{...t(),version:'latest'},{...t(),name:'a'.repeat(61)}]) assert.throws(()=>core.parseTemplate(v)); });
test('template swap preserves site/theme and restores hidden content', () => { const p=core.newProject(t()); p.site.name='Nahuel ñ'; p.theme.material='glass'; p.hidden=['faq']; const next=core.swapTemplate(p,{...t(),id:'atlas',layout:'editorial',sections:['hero','catalog']}); assert.deepEqual(next.site,p.site); assert.deepEqual(next.theme,p.theme); assert.deepEqual(next.hidden,p.hidden); });
test('unsupported material has explicit fallback only', () => { const p=core.newProject(t()); p.theme.material='glass'; const n=core.swapTemplate(p,{...t(),materials:['flat']}); assert.equal(n.theme.material,'flat'); assert.equal(p.theme.material,'glass'); });
test('project round trip supports Unicode, rejects unsafe logo, css and unknown keys', () => { const p=core.newProject(t()); p.site.name='Universo ñ 漢字'; assert.deepEqual(core.parseProject(JSON.stringify(p)),p); for(const patch of [{accent:'red;}</style><script>'},{radius:100},{font:'url(evil)'}]) assert.throws(()=>core.parseProject({...p,theme:{...p.theme,...patch}})); assert.throws(()=>core.parseProject({...p,site:{...p.site,logo:'data:image/svg+xml;base64,PHN2Zz4='}})); });
test('size limits apply before JSON parse', () => { assert.throws(()=>core.parseTemplate(' '.repeat(core.MAX_TEMPLATE_BYTES+1))); assert.throws(()=>core.parseProject(' '.repeat(core.MAX_PROJECT_BYTES+1))); });
test('share link round trip is portable with embedded template, excludes logo', () => { const p=core.newProject(t()); p.site.name='Mi marca ñ 漢字'; const hash=core.encodeShare(p); const n=core.decodeShare(hash); assert.equal(n.site.name,p.site.name); assert.deepEqual(n.template,p.template); assert.equal(n.site.logo,''); assert.throws(()=>core.decodeShare('#project=%%%')); });
test('template versions cannot be overwritten; new versions coexist', () => { const a=t(); const c=core.addTemplate([a],a); assert.equal(c.length,1); assert.throws(()=>core.addTemplate([a],{...a,name:'Otro'})); assert.equal(core.addTemplate([a],{...a,version:'1.1.0'}).length,2); });
test('history keeps bounded snapshots and branches after undo', () => { const h=core.createHistory(0,3); h.push(1);h.push(2);h.push(3);h.push(4);assert.equal(h.undo(),3);assert.equal(h.undo(),2);assert.equal(h.redo(),3);h.push(7);assert.equal(h.canRedo,false);assert.equal(h.current,7); });
test('strict catalog validates every item, rejects duplicates and unsupported shape', () => { assert.equal(core.parseCatalog({format:'maker-catalog-1',templates:[t()]}).length,1); assert.throws(()=>core.parseCatalog({format:'maker-catalog-1',templates:[t(),t()]})); assert.throws(()=>core.parseCatalog({templates:[]})); });
