import { parseProject, ink, luminance } from './core.js';
export const escapeHTML = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7"/></svg>';
const star='<svg viewBox="0 0 100 100" fill="none" aria-hidden="true"><path d="M50 5 62 36 95 50 63 62 50 95 37 64 5 50 37 37Z" fill="currentColor"/><path d="m50 20 8 24 22 6-23 7-7 23-7-23-23-7 23-7Z" fill="#fff" opacity=".55"/></svg>';
const diamond='<svg viewBox="0 0 100 100" fill="none" aria-hidden="true"><path d="m15 34 18-20h34l18 20-35 53Z" fill="currentColor"/><path d="m15 34 35 53 15-53-15-20-15 20Zm0 0h70M33 14l2 20 15 53 17-73" stroke="#fff" stroke-width="2" opacity=".55"/></svg>';
const orb='<svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="33" fill="currentColor"/><ellipse cx="50" cy="50" rx="16" ry="33" fill="none" stroke="white" stroke-width="2" opacity=".5"/><ellipse cx="50" cy="50" rx="33" ry="12" fill="none" stroke="white" stroke-width="2" opacity=".5"/><ellipse cx="50" cy="50" rx="47" ry="16" transform="rotate(-30 50 50)" fill="none" stroke="currentColor" stroke-width="5"/></svg>';
function rgb(hex){return hex.slice(1).match(/../g).map(v=>parseInt(v,16)).join(',');}
export function renderSite(input) {
  const p=parseProject(input),s=p.site,t=p.template,th=p.theme,e=escapeHTML;
  const sections=[...p.order,...t.sections.filter(k=>!p.order.includes(k))].filter(k=>t.sections.includes(k)&&!p.hidden.includes(k));
  const destination=sections.includes('catalog')?'catalog':sections.find(k=>k!=='hero')||'hero';
  const dark=luminance(th.background)<.3;
  const vars=`--mk-accent:${th.accent};--mk-accent-rgb:${rgb(th.accent)};--mk-bg:${th.background};--mk-ink:${ink(th.accent)};--mk-text:${dark?'#f5f5f8':'#15151c'};--mk-muted:${dark?'#aaaab8':'#4d4d5b'};--mk-panel:${dark?'27,28,36':'242,243,250'};--mk-border:${dark?'255,255,255':'12,12,30'};--mk-radius:${th.radius}px;--mk-blur:${th.blur}px;--mk-opacity:${th.opacity/100};--mk-columns:${t.columns};`;
  const nav=sections.filter(k=>k!=='hero').slice(0,4).map(k=>`<a href="#mk-${k}">${e(s.sectionTitles[k])}</a>`).join('');
  const heading=(key,label)=>`<div class="mk-section-heading"><div><span class="mk-eyebrow">${label}</span><h2>${e(s.sectionTitles[key])}</h2></div><span class="mk-tiny">CONTENIDO DE MUESTRA</span></div>`;
  const blocks={
    hero:()=>`<section id="mk-hero" class="mk-hero mk-surface mk-hero-${t.hero}"><div class="mk-hero-copy"><span class="mk-eyebrow"><i></i>${e(s.tagline)}</span><h1>${e(s.title).replaceAll('\n','<br> ')}</h1><p>${e(s.description)}</p><a class="mk-primary" href="#mk-${destination}">${e(s.cta)}${arrow}</a><div class="mk-hero-note"><span class="mk-dot"></span>Tu identidad. Tu espacio. Tu experiencia.</div></div><div class="mk-hero-art" aria-hidden="true">${s.heroImage?`<img src="${e(s.heroImage)}" alt="">`:`<div class="mk-orbit mk-orbit-one"></div><div class="mk-orbit mk-orbit-two"></div><div class="mk-chip mk-chip-back"><b>✦</b></div><div class="mk-chip mk-chip-front"><b>${e(s.name.slice(0,1).toUpperCase())}</b><span>YOUR UNIVERSE</span></div><div class="mk-floating mk-floating-star">${star}</div><div class="mk-floating mk-floating-diamond">${diamond}</div><span class="mk-art-label">DISEÑADO PARA DESTACAR</span>`}</div></section>`,
    categories:()=>`<section id="mk-categories">${heading('categories','EXPLORÁ')}<div class="mk-categories">${[['En vivo','Experiencias que conectan',orb],['Colecciones','Encontrá tu próxima favorita',diamond],['Especiales','Siempre algo por descubrir',star]].map(([name,subtitle,art],i)=>`<a class="mk-category mk-surface" href="#mk-${destination}"><span class="mk-category-art" style="--mk-shift:${i*45}deg">${art}</span><div><span class="mk-eyebrow">0${i+1}</span><h3>${name}</h3><p>${subtitle}</p></div><span class="mk-round-arrow">${arrow}</span></a>`).join('')}</div></section>`,
    catalog:()=>`<section id="mk-catalog">${heading('catalog','DESCUBRÍ')}<div class="mk-catalog">${[['COSMIC','Órbita infinita',265,orb],['GOLDEN','Hora dorada',35,diamond],['NEON','Ciudad neón',320,star],['EMERALD','Horizonte verde',160,diamond],['LUNAR','Lado lunar',215,orb],['NOVA','Otra dimensión',15,star]].map(([small,name,hue,art],i)=>`<article class="mk-card mk-surface"><div class="mk-card-art" style="--mk-card-hue:${hue}"><span class="mk-card-kicker">${small}</span><div>${art}</div><span class="mk-card-number">0${i+1}</span></div><div class="mk-card-caption"><div><h3>${name}</h3><p>Colección de muestra</p></div><span class="mk-card-mark">✦</span></div></article>`).join('')}</div></section>`,
    features:()=>`<section id="mk-features" class="mk-features mk-surface"><div><span class="mk-eyebrow">HECHO A TU MEDIDA</span><h2>${e(s.sectionTitles.features)}</h2><p>Un mismo universo, en todas tus pantallas.</p></div><div class="mk-feature"><span>01</span><h3>Identidad propia</h3><p>Tu marca en cada detalle.</p></div><div class="mk-feature"><span>02</span><h3>Diseño adaptable</h3><p>Del escritorio a tu bolsillo.</p></div><div class="mk-feature"><span>03</span><h3>Una experiencia</h3><p>Clara, simple y consistente.</p></div></section>`,
    faq:()=>`<section id="mk-faq" class="mk-faq">${heading('faq','SIN VUELTAS')}<details class="mk-surface"><summary>¿Qué estoy viendo?<span>+</span></summary><p>Una vista de diseño creada con Maker. El catálogo es ilustrativo y no ofrece juegos, pagos ni cuentas reales.</p></details><details class="mk-surface"><summary>¿Se adapta al celular?<span>+</span></summary><p>Sí. La distribución se adapta al ancho de tu pantalla y conserva la identidad visual.</p></details></section>`
  };
  return `<div class="mk-site mk-font-${th.font}" data-layout="${t.layout}" data-material="${th.material}" style="${vars}"><a class="mk-skip" href="#mk-hero">Saltar al contenido</a><header class="mk-header mk-surface"><a class="mk-brand" href="#mk-hero">${s.logo?`<img src="${e(s.logo)}" alt="">`:`<span class="mk-brand-mark">${star}</span>`}<span>${e(s.name)}</span></a><nav aria-label="Navegación del sitio">${nav}</nav><span class="mk-demo-label">VISTA DE DISEÑO</span></header><div class="mk-layout">${t.layout==='sidebar'?`<aside class="mk-side mk-surface"><span class="mk-eyebrow">TU UNIVERSO</span>${nav}<span class="mk-side-bottom">Diseño de muestra<br>Sin operaciones reales</span></aside>`:''}<main class="mk-main">${sections.map(k=>blocks[k]()).join('')}<footer class="mk-footer"><strong>${e(s.name)}</strong><span>Vista de diseño · Sin juegos, pagos ni cuentas reales.</span><span>Hecho con Maker</span></footer></main></div></div>`;
}
export function toDocument(project, trustedCSS) {
  const p=parseProject(project);
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"><title>${escapeHTML(p.site.name)}</title><style>${trustedCSS}</style></head><body>${renderSite(p)}</body></html>`;
}
